spring:
  cloud:
    gateway:
      routes:
        - id: patients-service
          uri: http://backend-patients:8081
          predicates:
            - Path=/api/patients/**
        - id: notes-service
          uri: http://backend-notes:8082
          predicates:
            - Path=/api/notes/**
        - id: risk-service
          uri: http://backend-risk:8083
          predicates:
            - Path=/api/risk/**