CREATE TABLE IF NOT EXISTS "user"
(
	id         BIGINT AUTO_INCREMENT PRIMARY KEY,
	username   VARCHAR(255) NOT NULL UNIQUE,
	password   VARCHAR(255) NOT NULL,
	shown_name VARCHAR(255) NOT NULL,
	roles      VARCHAR(255)
);
